version: "3"

networks:
  rope-net:
    external: true

services:
  webapp:
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
      - 25:25
    expose:
      - 25
      - 8000  
    volumes:
      - "./src:/src"
      - "/etc/localtime:/etc/localtime"
    env_file:
      - .django.env
    command: gunicorn --access-logfile ../access.log --error.logfile ../error.log ropd.wsgi:application -w 2 -b :8000
    links:
      - redis
    networks:
      - rope-net  

  webproxy:
    restart: always
    build: ./webproxy/nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./src/static:/www/static"
      - "./src/media:/www/media"

      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/var/lib/letsencrypt:/var/lib/letsencrypt"
      - "/etc/localtime:/etc/localtime"
    links:
      - redis
      - webapp:webapp
    environment:
      - PORT_REDIS=6379
      - HOST_REDIS=redis

    networks:
      - rope-net  
  ### PostgreSQL Container (Master) ####################################

  master:
    restart: always
    build: ./pg_db/pg_master
    volumes:
      - master_vol:/var/lib/postgresql
      - "/etc/localtime:/etc/localtime"
    ports:
      - "5434:5432"
    env_file:
      - ./pg_db/pg_master/.master.env
    networks:
      - rope-net  
  ### PostgreSQL Container (Slave) ####################################

  slave:
    restart: always
    build: ./pg_db/pg_slave
    volumes:
      - slave_vol:/var/lib/postgresql
      - "/etc/localtime:/etc/localtime"
    ports:
      - "5435:5432"
    links:
      - master:master
    env_file:
      - ./pg_db/pg_slave/.slave.env
    networks:
      - rope-net
  ### pgAdmin Container (Master) #######################################

  pgadmin:
    build: ./pg_db/pgadmin
    ports:
      - "5051:5051"
    env_file:
      - ./pg_db/pgadmin/pg4.env
    links:
      - master
    networks:
      - rope-net
  ### REDIS Container ##################################################
  redis:
    restart: always
    image: redis:3.2.0
    expose:
      - "6379"
    volumes:
      - redis_vol:/data
      - "/etc/localtime:/etc/localtime"
    networks:
      - rope-net

volumes:
  master_vol:
    driver: "local"
  slave_vol:
    driver: "local"
  sessions: ## nothing is connected to this (- ./data/sessions:/sessions)
    driver: "local"
  redis_vol:
    driver: "local"
